---
title: Umsetzungsphase bis Mitte 2021
description: |
  Dank dem Erfolg der konzeptionellen ersten Projektphase (vgl. Schlussbericht Phase 1) konnte Wiesel & Co am Zimmerberg Ende 2015 wie geplant in die Umsetzungsphase starten. Sie wird von den Resultaten aus dem ersten Projektjahr profitieren; Kontakte mit verschiedenen Interessengruppen, Planungsinstrumente und Know-How bei der Erstellung von Massnahmen in der Landschaft sowie bei der Wirkungskontrolle sind beste Voraussetzung dafür.Das Projekt wird am 31. Mai 2021 beendet werden.Den Beschrieb der Phase 2 inkl. der referenzierten Anhänge finden Sie nachfolgend:
author: natursc
date: 2016-01-18
categories:
  - 
output:
  distill::distill_article:
    self_contained: false
canonical: /projekt/ausgangslage/66-beschrieb-umsetzungsphase
---


**Dank dem Erfolg der konzeptionellen ersten Projektphase ([vgl.
Schlussbericht Phase
1](images/dokumente/AnhangA_WiCoZ_Phase_1_Schlussbericht_2015_06_20.pdf))
konnte Wiesel & Co am Zimmerberg Ende 2015 wie geplant in die
Umsetzungsphase starten. Sie wird von den Resultaten aus dem ersten
Projektjahr profitieren; Kontakte mit verschiedenen Interessengruppen,
Planungsinstrumente und Know-How bei der Erstellung von Massnahmen in
der Landschaft sowie bei der Wirkungskontrolle sind beste Voraussetzung
dafür. Den Beschrieb der Phase 2 inkl. der referenzierten Anhänge finden
Sie nachfolgend:**

-   [Phase 2:
    Projektbeschrieb](images/dokumente/beschrieb_umsetzungsphase/WiCoZ_Phase_2_Projektbeschrieb.pdf)
-   [Anhang A - Schlussbericht Phase
    1](images/dokumente/AnhangA_WiCoZ_Phase_1_Schlussbericht_2015_06_20.pdf)
-   [Anhang B -
    Lebensraumanalyse](images/dokumente/beschrieb_umsetzungsphase/AnhangB_Ratnaweera_Tutorial_II_red.pdf)
-   [Anhang C - Patch- und
    Vernetzungsplanung](images/dokumente/beschrieb_umsetzungsphase/AnhangC_Patch_Vernetzungsplanung.pdf)
-   [Anhang D - Strukturen in der Direktzahlungsverordnung und in
    Label-Programmen](images/dokumente/beschrieb_umsetzungsphase/Strukturen_DZV_Label_Staeheli2016.pdf)
-   [Anhang E - Massnahmenliste Landschaftsqualitätsprojekt Zürich
    Süd](images/dokumente/beschrieb_umsetzungsphase/AnhangE_massnahmenliste_lqp_sued.pdf)
-   [Anhang F - Bonussystem](images/dokumente/Bonussystem_WiCoZ.pdf)

Gemäss [Projektbeschrieb der Projektphase
2](projekt/ausgangslage/66-beschrieb-umsetzungsphase) war das bisherige
offizielle Projektende der 31. Mai 2020.   
Es ist eine Tatsache, dass die Trägerschaft gut mit seinem Budget
gehaushaltet und dennoch bereits viele seiner Ziele erreicht hat.   
Dies erlaubt dem Projekt bei gleichbleibendem Finanzierungsplan und
unveränderten Projektzielen 1 Jahr länger die Lebensräume von Wiesel &
Co zu vernetzen.

[Unsere Partner](ueber-uns/7-partner) haben nichts dagegen einzuwenden.
Wir bedanken uns für Ihr Vertrauen.

Die Trägerschaft kann sich somit auf ein zusätzliches produktives
Projektjahr freuen. Der Fokus liegt u.a.  auf der Sanierung von
Feldscheunen, der Erarbeitung von Grossstrukturen und der Durchführung
von Wieselwerken mit Schulklassen.  
Dahingehend profitieren alle Interessengruppen von dem, was das Projekt
schon an Grundlagen geschaffen hat und in der Endphase noch vollenden
bzw. abrunden kann.

<!--http://wieselundco.ch/projekt/ausgangslage/66-beschrieb-umsetzungsphase-->
