---
title: 'Ihr Team in Aktion'
description: |
  Im Winterhalbjahr bot Wiesel & Co am Zimmerberg Aktionstage exklusiv für Teams an.  
  
    Für Gruppen (z.B. Mitarbeiter von Unternehmen), die Ihre Gemeinschaft einmal anders erleben möchten, bot die tatkräftige Lebensraumaufwertung im Bezirk Horgen eine ideale Gelegenheit. Wir gignen auf die jeweiligen Bedürfnisse ein und fanden für  den geeigneten Aktionsort.
    
      Welche Gründe sprachen für das Angebot von Wiesel & Co am Zimmerberg?. 
date: 2020-04-08
preview: Team_in_Aktion_WiCoZ.JPG
image_intro: images/dokumente/Team_in_Aktion_WiCoZ.JPG
output:
  distill::distill_article:
    self_contained: false
canonical: /mithelfen-anpacken/mithelfen/75-teamtraining-mit-wiesel-co-am-zimmerberg-2
params:
  rmdpath: _mithelfen-anpacken-mithelfen/75-teamtraining-mit-wiesel-co-am-zimmerb/75-teamtraining-mit-wiesel-co-am-zimmerb.Rmd
  editurl: https://github.com/wieselundco/website/edit/master/
---

Für Gruppen (z.B. Mitarbeiter von Unternehmen), die Ihre Gemeinschaft einmal anders erleben möchten, stellt die tatkräftige Lebensraumaufwertung im Bezirk Horgen eine ideale Gelegenheit dar.

Für viele Menschen findet der Alltag in Gebäuden statt, öfters vor dem Computer. So auch bei Ihnen?

Wünschten Sie sich einen Tag mit Ihren KameradInnen unter freiem Himmel? 

Mit Wiesel & Co am Zimmerberg ist dies möglich und gleichzeitig schaffen Sie mit Ihren eigenen Händen wertvolle Verstecke und Nistmöglichkeiten für Kleinraubtiere.

Tauchen Sie ein in die Lebenswelt von Wiesel & Co, nutzen Sie den Raumwechsel und schöpfen Sie im Feld Inspiration & Lust für die weitere Gemeinschaft im Team.

Das Angebot für solche gemeinsame "Wieselwerke" ist in der Regel in den Monaten November bis März möglich. Wir gehen auf Ihre Bedürfnisse ein und finden für Ihr Team den geeigneten Aktionsort. 




```{r,results='asis', echo = FALSE}



```

<!--http://wieselundco.ch/mithelfen-anpacken/mithelfen/75-teamtraining-mit-wiesel-co-am-zimmerberg-2-->
