---
title: 'Gemischtes Doppel'
description: |
  Vor einigen Jahren konnte Familie Baruffol in Kilchberg mehrere Wiesel sichten. Lesen Sie selbst die Geschichte einer erstaunlichen Beobachtung von Wieseln.
date: 2014-01-27
preview: Frau_Baruffol.jpg
image_intro: images/fotos/2014_01_27_Gemischtes_Doppel/Frau_Baruffol.jpg
output:
  distill::distill_article:
    self_contained: false
canonical: /faszination-kleinraubtiere/mensch-wiesel/8-gemischtes-doppel
params:
  rmdpath: _faszination-kleinraubtiere-mensch-wiesel/8-gemischtes-doppel/8-gemischtes-doppel.Rmd
  editurl: https://github.com/wieselundco/website/edit/master/
---

Wiesel & Co, Interview mit Martha Baruffol, Kilchberg  
  
Martha Baruffol, Wann haben Sie die Wiesel erstmals beobachtet?  
  
*Das war vor gut 25 Jahren. Damals spielte noch unsere ganze Familie
Tennis. Wir waren also oft  im Gebiet Chirchmoos dort wo auch die
Tennisplätze sind.*

<!-- {vsig}fotos/2014\_01\_27\_Gemischtes\_Doppel{/vsig} -->

{vsig\_c}0|Frau\_Baruffol.jpg|Frau Baruffol zeigt die Wasser-Rinne wo
die Wiesel herauskamen|{/vsig\_c}

{vsig\_c}0|Wasserrinne.jpg|Wasser-Rinne entlang Tennisplatz|{/vsig\_c}

  
Wie genau haben sich die Wiesel gezeigt?  
  
*Während die Kinder Tennis spielten, lugten plötzlich die Köpfchen von
drei kleinen Wieseln aus der Wasserrinne am Rand des Spielfelds. Sie
sprangen hinaus und hinein und  rannten auf dem Platz den Bällen nach.
Es waren drei kleinere, also Junge und ein oder zwei Erwachsene.*

  
Was haben Sie dabei empfunden? Freude, Verwunderung oder vielleicht
Ärger?  
  
*Grosse Freude. Meine Tochter hiess damals nämlich in der Pfadi Wiesel.
Ich habe mich also ganz besonders gefreut über das zufällige
„Zusammenspiel der zwei-und vierbeinigen Wiesel“.*  
  
War dies eine einmalige Beobachtung?  
  
*Nein. Während wir Eltern unseren Kindern beim Spielen zuschauten
zeigten sich die Tierchen noch mehrmals in den folgenden Wochen.*  
  
Haben Sie später noch einmal eine Wieselbeobachtung gemacht?  
  
*Nein, leider nicht. Aber mein Mann hat im Jahr 2008 noch einmal ein
Wiesel an diesem Ort gesichtet.*  
  
Sie spielen immer noch aktiv Tennis. Werden Sie dabei auch in Zukunft
Ausschau nach den sympathischen Räubern halten?  
  
*Ja, auf jeden Fall. Ich werde ausserdem die Mitlglieder und den
Platzwart bitten, allfällige Beobachtungen zu melden.*  
  
Ich bedanke mich ganz herzliche für dieses Gespräch und wünsche Ihnen
noch viele vergnügliche „gemischte Doppel“.  
  
Interview: Susanne Heusser

 

```{r,results='asis', echo = FALSE}
pander::pandoc.horizontal.rule()

pander::pandoc.link(url = glue::glue('{params$editurl}{params$rmdpath}'),text = 'Artikel bearbeiten')
```

<!--http://wieselundco.ch/faszination-kleinraubtiere/mensch-wiesel/8-gemischtes-doppel-->
