---
title: 'Who is Who? Unsere Zielarten'
description: |
  Flink hüpfen Hermelin und Mauswiesel über die Wiese. Hin und wieder verschwinden sie in der Erde. Hier jagen die geschickten Räuber langgestreckt und mit kurzen Beinen den Wühlmäusen in ihren Gängen nach.
date: 2014-01-28
preview: 3_iltis.jpg
image_intro: images/bilder/arten/proportional/3_iltis.jpg
output:
  distill::distill_article:
    self_contained: false
canonical: /faszination-kleinraubtiere/unsere-leitarten/12-who-is-who
params:
  rmdpath: _faszination-kleinraubtiere-unsere-leitarten/12-who-is-who/12-who-is-who.Rmd
  editurl: https://github.com/wieselundco/website/edit/master/
---

In den engen Mäusebauten können die Wiesel sich keine Fettreserven
erlauben und so sind sie im ständigen Wechsel von Ruhe- und
Aktivitätsphasen. Daher lassen sich die neugierigen Tiere über das ganze
Jahr und zu jeder Tages- und Nachtzeit beobachten.

{gallery}bilder/arten/proportional{/gallery}


|                  	| Mauswiesel                                                  	| Hermelin                                                                                                              	| Iltis                                                             	|
|------------------	|-------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------	|-------------------------------------------------------------------	|
| Kopf-Rumpf-Länge 	| 20cm                                                        	| 30cm                                                                                                                  	| 40cm                                                              	|
| Schwanz Länge    	| 5cm                                                         	| 15cm                                                                                                                  	| 15cm                                                              	|
| Fellfärbung      	| Ganzjährig braun-weiss Unruhige Trennlinie Ober-/Unterseite 	| Auffälliger Schwanz mit schwarzer Schwanzspitze Weisses Winterfell  Scharfe Trennlinie Ober-/Unterseite im Sommerfell 	| Unverkennbare Gesichtsmaske Dunkle Grannenhaare, beige Unterwolle 	|
|                  	|                                                             	|                                                                                                                       	|                                                                   	|
 

[Kurzporträts aller Säugetiere der Schweiz finden Sie
online](https://apps.wildtier.ch/mammals/) oder im 2021 erschienenen
[Atlas der
Säugetiere](https://www.haupt.ch/buecher/natur-garten/atlas-der-saeugetiere-schweiz-und-liechtenstein.html)
der [Schweizerischen Gesellschaft für
Wildtierbiologie](https://mitglied.scnat.ch/sgw-ssbf). 

 

 

 

```{r,results='asis', echo = FALSE}
pander::pandoc.horizontal.rule()

pander::pandoc.link(url = glue::glue('{params$editurl}{params$rmdpath}'),text = 'Artikel bearbeiten')
```

<!--http://wieselundco.ch/faszination-kleinraubtiere/unsere-leitarten/12-who-is-who-->
