---
title: Souvenir! Taten der Saison 2016/7.
description: |
  Der Rückblick auf die Saison lohnt auch dieses Jahr! Engagierte Naturfreunde sorgten für weitere Dutzende Aufwertungsmassnahmen und zwar an 16 Orten im Bezirk Horgen. Seit dem Frühjahr 2016 bieten damit stolze 174 neu erstellte Asthaufen, Winterquartiere, Gebüschgruppen und Gross-Strukturen Wiesel & Co Unterschlupf.
author: natursc
date: 2017-06-21
categories:
  - resultate
output:
  distill::distill_article:
    self_contained: false
canonical: /projekt/resultate/97-souvenir-2016-7
---


**Der Rückblick auf die Saison lohnt auch dieses Jahr!**

**Engagierte Naturfreunde sorgten für weitere Dutzende
Aufwertungsmassnahmen und zwar an 16 Orten im Bezirk Horgen.**

**Seit dem Frühjahr 2016 bieten damit stolze 174 neu erstellte
Asthaufen, Winterquartiere, Gebüschgruppen und Gross-Strukturen Wiesel &
Co Unterschlupf. **

[Wie bereits
berichtet](projekt/resultate/94-feldscheunen-sanierung-2016-7) starteten
zudem erste Sanierungen von Feldscheunen. 

Die zunehmende Vernetzung der Lebensräume haben wir weitsichtigen
Landwirten, Schulklassen, Jugendlichen von Jungwacht Blauring,
Landschaftspflegern der öffentlichen Hand, interessierten
KursteilnehmerInnen und vielen weiteren tollen Personen zu verdanken.

Der Dank kommt denn auch direkt von den Kleinraubtieren, die schon
wieder am einen oder anderen Ort ihre Abdrücke in den Spurenfallen
hinterlassen haben...

Und jetzt zu den Souvenirs - in Form unverstaubter Bilder:

{gallery}fotos/Saison\_2016\_7{/gallery}

<!--http://wieselundco.ch/projekt/resultate/97-souvenir-2016-7-->
