---
title: 'Bekämpfung mit Verstand'
description: |
  Eine Massenvermehrung von Wühlmäusen wünscht sich kein Produzent in seinen Kulturen. Mit einer steten Bekämpfung bzw. Bejagung ist ein solches Ereignis sehr unwahrscheinlich.  Natürliche Feinde wie Greif- und Schreitvögel, Fuchs und Hauskatze und insbesondere die beiden Wieselarten sorgen zuverlässig für diese Regulierung, falls Ihnen ein geeigneter Lebensraum zugestanden wird. Greifvögeln kann beispielsweise mit Sitzstangen gut die Jagd erleichtert werden.  Im Fall von Wieseln werden dahingehende Lebensraumaufwertungen durch unser Projekt gefördert. Wiesel sind insofern gegenüber anderen Jägern im Vorteil, als dass sie in die Gänge der Wühlmäuse vordringen und damit sogar deren Brut rauben können. Pro Woche vertilgt ein Hermelin ca. 10 Wühlmäuse. Während der Jungenaufzucht werden für die durchschnittlich 8 Jungen weitere ca.  15 Mäuse pro Woche benötigt!   
date: 2018-02-13
preview: hermelin-mit-fetter-beute-974efa75-6f44-49f1-bf21-c088b1e32468.jpg
image_intro: images/Workshops_Kurstage/Wuehlmaeuse_im_Griff/hermelin-mit-fetter-beute-974efa75-6f44-49f1-bf21-c088b1e32468.jpg
output:
  distill::distill_article:
    self_contained: false
canonical: /faszination-kleinraubtiere/wuehlmaeuse/104-bekaempfung-mit-verstand
params:
  rmdpath: _faszination-kleinraubtiere-wuehlmaeuse/104-bekaempfung-mit-verstand/104-bekaempfung-mit-verstand.Rmd
  editurl: https://github.com/wieselundco/website/edit/master/
---

Diese "Ökosystemleistung" erfordert von den Bewirtschaftern einzig eine vernünftige, ökologische Anordnung und Ausstattung ihrer Bewirtschaftungsflächen. Gleichzeitig muss unbedingt auf die Bekämpfung der Wühlmäuse mittels Giftködern verzichtet werden. Die Vergasung (z.B. mittels "Mauki") sollte ebenfalls sehr zurückhaltend angewendet werden, da sich Wiesel oft in den Gängen aufhalten, ja teilweise sogar dort vermehren. In die mechanischen Fallen geraten die Wiesel jedoch recht selten - Zugleich ist dies die verlässlichste Methode, um den Wühlmausbestand sehr niedrig zu halten.    Unter geeigneten Voraussetzungen kann ein fix installierter Mäusezaun ein sehr wirksames Element bei der Bekämpfung von Wühlmausschäden sein. Die Zuwanderung der Nager wird damit stark erschwert.  




```{r,results='asis', echo = FALSE}
pander::pandoc.horizontal.rule()

pander::pandoc.link(url = glue::glue('{params$editurl}{params$rmdpath}'),text = 'Artikel bearbeiten')
```

<!--http://wieselundco.ch/faszination-kleinraubtiere/wuehlmaeuse/104-bekaempfung-mit-verstand-->
