---
title: 'Warum hilft meine Beobachtungs-Meldung?'
description: |
  Verlässliche Daten über die Kleinraubtier-Bestände und ihre Entwicklung fehlen schweizweit. 
  
    Selbst die Verbreitungskarten, die das Centre Suisse de Cartographie de la Faune (www.cscf.ch) anhand den vorhandenen Daten zeigt, sind mit Vorsicht zu geniessen. Offensichtlich beeinflussen regionale Erhebungen die zitierten Verbreitungskarten so stark, dass sie ein falsches Abbild der Artvorkommen suggerieren könnten. So resultierte aus einem kürzlich erfolgten Monitoring im Kanton Aargau, dass der Baummarder dort weit verbreitet ist. Vergleichbare Landschaften angrenzender Kantone zeigen hingegen auf der Verbreitungskarte eine auffallend lückige Verbreitung. 
  
    Das fehlende Wissen über das Vorkommen von Kleinraubtieren wird damit augenfällig. Welche Gründe gibt es dafür?
date: 2014-02-01
output:
  distill::distill_article:
    self_contained: false
canonical: /mithelfen-anpacken/beobachtung/28-warum-und-wozu-hilft-meine-sichtungs-meldung
params:
  rmdpath: _mithelfen-anpacken-beobachtung/28-warum-und-wozu-hilft-meine-sichtungs-/28-warum-und-wozu-hilft-meine-sichtungs-.Rmd
  editurl: https://github.com/wieselundco/website/edit/master/
---

### Erstens: Das Verhalten.

Die verschiedenen Kleinraubtierarten begegnen dem Menschen wenig,
bedingt u.a. durch folgende Verhaltensweisen:

- Zum Teil dämmerungs- und nachtaktiv
- Aufenthalt und Fortbewegung oft in Deckung oder in Erdlöchern.
- flinke Fortbewegungsweise
- per se klein, somit auch der Ort für Unterschlupf und ihre Spuren.
- Tote Tiere (auch Verkehrsopfer) werden übersehen und rasch von
    Aasfressern abgeräumt.

Wenn wir auf ihre Sichtung zählen dürfen, erhöht sich die Zahl der registrierten Begegnungen und wir erfahren zumindest am Zimmerberg mehr über die Verbreitung und ansatzweise etwas über die Bestände der Kleinraubtiere.

### Zweitens: Die öffentliche Hand kann zu wenig ihrer Verantwortung gegenüber gefährdeten Arten gerecht werden.

Jagd und Schutz der Kleinraubtiere unterstehen laut Gesetz der Jagd- und
Fischereiverwaltung des Kantons Zürich. Sie interessiert sich im
Wesentlichen für die attraktiven jagdbaren Arten, wozu die
Kleinraubtiere nicht zählen.

Eine Aufgabe der Fachstelle für Naturschutz des Kantons Zürich besteht
darin, dem Aussterben von Pflanzen- und Tierarten entgegenzuwirken.
Angesichts der vielen bedrohten Arten und beschränkten Mittel werden
aber momentan vor allem prioritäre Arten mit Aktionsplänen artspezifisch
gefördert. Hier kommen Mauswiesel und Iltis zu kurz; Ein Aktionsplan
scheint ausser Reichweite obwohl sie auf der [Roten
Liste](http://www.artenschutz.ch/RLDetails/RL1_S%C3%A4uger.pdf)
erscheinen.

Die Datenlücken der Kleinraubtier-Bestände dürften mit ein Grund sein
dafür, dass ein gezielter Schutzbedarf gemäss der Liste der national
prioritären Arten des Bundesamts für Umwelt für Mauswiesel und Iltis als
"unsicher" taxiert wird. 

Mit ihrer Sichtungs-Meldung tragen Sie dazu bei, den Handlungsbedarf
in Bezug auf die Kleinraubtiere zu klären. 

```{r,results='asis', echo = FALSE}



```

<!--http://wieselundco.ch/mithelfen-anpacken/beobachtung/28-warum-und-wozu-hilft-meine-sichtungs-meldung-->
