---
title: 'Inspiration'
description: |
  'Der Naturschutzverein Schönenberg (NVS) wurde durch die Stiftung Wieselnetz (WIN) auf die Thematik der Kleinraubtiere aufmerksam und realisierte mit deren Unterstützung von 2009-2012 ein Wieselprojekt auf ihrem Gemeindegebiet. Die Projektierung erfolgte so überzeugend, dass innert kurzer Frist die nötigen finanziellen Mittel zur Realisierung des Projekts von privaten wie öffentlichen Geldgebern gesprochen wurden.'
date: 2014-01-28
preview: haufenbau_2.jpg
image_intro: images/fotos/diverse/haufenbau_2.jpg
output:
  distill::distill_article:
    self_contained: false
canonical: /projekt/ausgangslage/11-das-wieselfoerderprojekt-der-gemeinde-schoenenberg-2009-2012
params:
  rmdpath: _projekt-ausgangslage/11-das-wieselfoerderprojekt-der-gemeinde/11-das-wieselfoerderprojekt-der-gemeinde.Rmd
  editurl: https://github.com/wieselundco/website/edit/master/
---




**<span style="line-height: 1.3em;">Der NVS profitierte von der
Zusammenarbeit mit WIN u.a. vom Netzwerk von Fachpersonen und von einem
erprobten Förderkonzept, welches messbare Erfolge brachte: Potentielle
Lebensräume wurden ausgeschieden, förderliche Kleinstrukturen wie
Asthaufen im Rahmen von öffentlichen Arbeitseinsätzen erstellt und die
Wirkungskontrolle zeigte deutlich, dass nach der Aufwertung die
entsprechenden Lebensräume von den Zielarten besucht wurden. Rege
Öffentlichkeitsarbeit leistete einen Beitrag zur Vermittlung der Inhalte
des Förderprojekts weit über die Vereinsgrenzen hinaus.</span>**

------------------------------------------------------------------------

[{vsig}fotos/2014\_01\_28\_NSV\_Schoenenberg{/vsig}](http://www.nv-schoenenberg.ch/joomla/index.php)  
{vsig\_c}0|haufenbau.jpg|Bau von Asthaufen nach
Wieselnetz-Art|{/vsig\_c}  
{vsig\_c}0|hermelin\_fotofalle.jpg|Normalerweise sind Hermeline zu flink
für die Fotofalle - dieser Nachweis bildet eine erfreuliche
Ausnahme!|{/vsig\_c}{vsig\_c}0|iltis\_spurenfalle.jpg|Ilits und Mäuse
haben Spuren hinterlassen|{/vsig\_c}

<span style="line-height: 1.3em;">Interessierten Lesern steht der
Schlussbericht des Projekts zum
</span>[Download](images/dokumente/Schlussbericht_Schoenenberg.pdf)<span
style="line-height: 1.3em;"> bereit. Die Website des
</span>[Naturschutzvereins
Schönenberg](http://www.nv-schoenenberg.ch/)<span
style="line-height: 1.3em;"> vermittelt zudem eindrückliche Bilder und
Worte.</span>

  
Das erfolgreiche Projekt zeigte schon während seiner Laufzeit Wirkung in
den benachbarten Naturschutzvereinen. Die wertvollen Erfahrungen und
Kontakte erleichterten es, nach Abschluss des offiziellen Rahmens 2012
weitere Aktionen zusammen mit Naturschutz Wädenswil auf
dessen Gemeindegebiet zu realisieren. Innert Jahresfrist einigten sich
die Naturschutzvereine des Bezirks Horgen auf eine Zusammenarbeit
zugunsten der Kleinraubtiere und geben der [Trägerschaft von Wiesel &
Co](ueber-uns/27-die-traegerschaft-wir-stellen-uns-vor) am Zimmerberg
die nötige Verankerung in der ganzen Region.

```{r,results='asis', echo = FALSE}
pander::pandoc.horizontal.rule()

pander::pandoc.link(url = glue::glue('{params$editurl}{params$rmdpath}'),text = 'Artikel bearbeiten')
```

<!--http://wieselundco.ch/projekt/ausgangslage/11-das-wieselfoerderprojekt-der-gemeinde-schoenenberg-2009-2012-->
