---
title: 'Sichtungskarte mit allen Beobachtungen von Wiesel & Co am Zimmerberg'
description: |
  Seit Beginn des Projekts wurde die Bevölkerung dazu aufgerufen, Beobachtungen von Kleinraubtieren zu melden. Meldungen wurden via das projekteigene Webtool, ein Faltblatt sowie per Mail oder auch mündlich aufgenommen. Die Beobachtungsmeldungen wurden in der Folge verifiziert und auf der Webkarte veröffentlicht. 
date: 2020-05-20
output:
  distill::distill_article:
    self_contained: false
canonical: /mithelfen-anpacken/beobachtung/39-zur-interaktiven-karte
params:
  rmdpath: _mithelfen-anpacken-beobachtung/39-zur-interaktiven-karte/39-zur-interaktiven-karte.Rmd
  editurl: https://github.com/wieselundco/website/edit/master/
---

Rund 600 Meldungen wurden als “plausibel” oder “sicher” beurteilt und sind auf der <a href="http://gis.lsfm.zhaw.ch/portal/apps/webappviewer/index.html?id=ab36b8f1202244b7bdcc860e06be2270" target="_blank">interaktiven Sichtungskarte von Wiesel & Co am Zimmerberg</a> abrufbar.

Dieser umfassende Datensatz wird übrigens auch in der <a href="http://erfolgskontrolle.wieselundco.ch/" target="_blank">Wirkungskontrolle der Aufwertungsmassnahmen für Wiesel und Co. am Zimmerberg</a> behandelt. 

Möglicherweise fragen Sie sich, warum das Mauswiesel in der Region so selten zu sein scheint?  [Wir haben auch nur vage Antworten.](21-Plakat Mauswiesel Erfassung_2021.pdf)

Folgend einige Tipps zur Benutzung der <a href="http://gis.lsfm.zhaw.ch/portal/apps/webappviewer/index.html?id=ab36b8f1202244b7bdcc860e06be2270" target="_blank">interaktiven Sichtungskarte von Wiesel & Co am Zimmerberg</a>:

- Die Legende kann über das linke Bedienfeld oben rechts in der Kopfzeile eingesehen werden.

- Beim Click auf einen Kartenpunkt werden Details zur realisierten Massnahme dargestellt.

- In der Layerliste (Bedienfeld "Ebenen" rechts davon) können die Planungsgrundlagen eingeblendet und transparent dargestellt werden.

- Abfragen können über das Lupensymbol getätigt und kombiniert werden. Das Ergebnis erscheint als Liste und als blaue Umrandung der zutreffenden Kartenpunkte.

- Zur kartographischen Orientierung können ganz rechts die gewünschte Hintergrundkarten gewählt und im Suchfeld oben links nach geografischen Namen (Flurnamen, Adressen, Gemeinden etc.) gesucht werden.




<!--http://wieselundco.ch/mithelfen-anpacken/beobachtung/39-zur-interaktiven-karte-->
