---
title: 'Trägerschaft und Ansprechpersonen'
description: |
  Für das im Jahr 2014 lancierte Projekt Wiesel & Co am Zimmerberg konnten sich acht Naturschutzvereine des Bezirks Horgen begeistern. Es sind dies sieben Sektionen des Bezirks Horgen des Dachverbandes BirdLife Zürich und der Verein Singdrossel von Langnau. Alle Vereine haben das Projekt die ganze Dauer über getragen. 
date: 2021-01-08


output:
  distill::distill_article:
    self_contained: false
canonical: /ueber-uns/27-die-traegerschaft-wir-stellen-uns-vor
params:
  rmdpath: _ueber-uns/27-die-traegerschaft-wir-stellen-uns-vor/27-die-traegerschaft-wir-stellen-uns-vor.Rmd
  editurl: https://github.com/wieselundco/website/edit/master/
---

Der NVV Hirzel fusionierte 2021 mir Natur Horgen. 

  Die untenstehenden Ansprechpersonen dürfen für Fragen und Anliegen auch nach Projektende kontaktiert werden.

```{r, echo = FALSE}

library(dplyr)
tribble(
  ~image, ~name, ~kontakt, ~email,
  "NVH_Logo_neu_grau.jpg", "Natur Horgen", "Thomas Rubin", "mailto:trubin@sunrise.ch",
  "Logo_NK_RGB_150dpi.jpg", "Naturschutz Kilchberg","Fabian Schwarzenbach", "mailto:fabian.schwarzenbach@bluemail.ch",
  "singdrossel_2.jpg", "Singdrossel Langnau","André Mauley", "mailto:a.mauley@hispeed.ch",
  "nsv_oberrieden_2.jpg", "Natur- und Vogelschutzverein Oberrieden","Maurus Frei", "mailto:maurus.frei@gruenliberale.ch",
  "nsv_richterswil.png", "Naturschutz Richterswil-Samstagern","Regula Büchler", "mailto:buechler@naturschutz-r-s.ch",
  "nsv_thalwil_2.gif", "Natur- und Vogelschutzverein Thalwil","Manuel Brändli", "mailto:braendli.manuel@gmx.ch",
  "NW_Logo_grau_280px.jpg", "Naturschutz Wädenswil","Sabina Stokar", "mailto:ss@naturwaedi.ch"
) -> df



df %>%
  mutate(
    image = "",
    kontakt = kableExtra::cell_spec(kontakt, "html", link = email)
    ) %>%
  select(-email) %>%
  kableExtra::kable(col.names = c("","", ""),escape = FALSE) %>%
  kableExtra::column_spec(1, image = df$image, width = "4cm") %>% kableExtra::kable_styling()


```

```{r,results='asis', echo = FALSE}



```

<!--http://wieselundco.ch/ueber-uns/27-die-traegerschaft-wir-stellen-uns-vor-->
