---
title: Bereits mehr als 100 Massnahmen realisiert
description: |
  Die seriöse Vorbereitung auf die Umsetzungsphase des Projekts in den Jahren 2014 und 2015 hat sich offensichtlich gelohnt. Dank den guten Kontakten mit Landwirten, Jägern und Förstern konnten im ersten Quartal 2016 bereits über hundert Massnahmen umgesetzt werden: Asthaufen, Winterquartiere, Gebüschgruppen und Gross-Strukturen.  Gelungen ist dies nicht zuletzt dank der massgeblichen Beteiligung der Ackerbaustellenleiter und Leiter von Vernetzungsprojekten.  Ohne das Mitwirken von unzähligen HelferInnen von Naturschutzvereinen, Pfadfinder-Abteilungen, Schulklassen, Jagdgesellschaften, Anwohnerschaften etc. wäre dies nicht möglich gewesen. Ihnen allen gebührt ein herzliches Dankeschön! Wiesel & Co am Zimmerberg blickt zuversichtlich auf den April und die kommenden Saisons voller Aufwertungsmassnahmen für die Lebensräume der Kleinraubtiere. Machen Sie sich ein Bild von den in schöner Erinnerung bleibenden Aktionstagen:
author: natursc
date: 2015-02-05
output:
  distill::distill_article:
    self_contained: false
canonical: /projekt/resultate/77-100-massnahmen-realisiert
---


Die seriöse Vorbereitung auf die Umsetzungsphase des Projekts in den
Jahren 2014 und 2015 hat sich offensichtlich gelohnt. Dank den guten
Kontakten mit Landwirten, Jägern und Förstern konnten im ersten Quartal
2016 bereits über hundert Massnahmen umgesetzt werden: Asthaufen,
Winterquartiere, Gebüschgruppen und Gross-Strukturen. 

Gelungen ist dies dank der massgeblichen
Beteiligung der Ackerbaustellenleiter, Leiter von Vernetzungsprojekten. 

Ohne das Mitwirken von unzähligen HelferInnen von Naturschutzvereinen,
Pfadfinder-Abteilungen, Schulklassen, Jagdgesellschaften,
Anwohnerschaften etc. wäre dies nicht möglich gewesen.

Ihnen allen gebührt ein herzliches Dankeschön! Wiesel & Co am
Zimmerberg blickt zuversichtlich auf den April und die kommenden Saisons
voller Aufwertungsmassnahmen für die Lebensräume der Kleinraubtiere.

 

 

Machen Sie sich ein Bild von den in schöner Erinnerung
bleibenden Aktionstagen: 

{gallery}fotos/Aktionstage\_Winter\_2015\_6{/gallery}

<!--http://wieselundco.ch/projekt/resultate/77-100-massnahmen-realisiert-->
