---
title: 'Geldgeber und Partner'
description: |
  Die acht Naturschutzvereine der Trägerschaft schätzen sich glücklich, auf folgende Geldgeber und Partner zählen zu können: 
date: 2016-01-15
output:
  distill::distill_article:
    self_contained: false
canonical: /ueber-uns/7-partner
params:
  rmdpath: _ueber-uns/7-partner/7-partner.Rmd
  editurl: https://github.com/wieselundco/website/edit/master/
---

```{r, echo = FALSE}

images <- c("Logo_lotteriefonds_ZH.jpg",
  "fls.jpg",
  "2480x236_logo_egs_schriftzug_schwarz.jpg",
  "temperatio.jpg",
  "Logo_gundlach.JPG",
  "Paul_Schiller_StiftungLogo.jpg",
  "horgen.png",
  "kilchberg.png",
  "langnau_am_albis.png",
  "richterswil.png",
  "thalwil.png",
  "waedenswil.png",
  "wieselnetz.jpg",
  "wls.gif",
  "LogoALN.jpg",
  "nsv_schoenenberg.png",
  "LOGO_BirdLife_NEU__farbe_cmyk__mittel_280pixel.jpg",
  "zhaw_lsfm.jpg",
  "logo-cscf-infofauna_sans-bordurered.jpg",
  "CashCtrl_Logo_height_50px.png",
  "Wz_logo_dgruen575_cmyk_280pixel.jpg",
  "jost_schnieder.png",
  "bocken.jpg",
  "syndrega_gmbh.jpg",
  "illustrat.png",
  "cigler_2.jpg",
  "Schluchtalhof_Schriftbild_snipe.JPG",
  "Logo_Streuli_cmyk_1200px.jpg",
  "hintermann_weber.jpg"
)


names <- c(
<a href="http://www.lotteriefonds.zh.ch/" target="_blank">Lotteriefonds Kanton Zürich</a>,
<a href="http://www.fls-fsp.ch/" target="_blank">Fonds Landschaft Schweiz</a>,
<a href="http://www.ernst-goehner-stiftung.ch/index.php/de" target="_blank">Ernst Goehner Stiftung</a>,
<a href="http://temperatio.ch/" target="_blank">Temperatio Stiftung</a> ,
"Graf Fabrice, von Gundlach und Payne Smith-Stiftung", 
<a href="http://www.paul-schiller-stiftung.ch/" target="_blank">Paul Schiller Stiftung</a>,
<a href="http://www.horgen.ch/" target="_blank">Gemeinde Horgen</a>,
<a href="http://www.kilchberg.ch/" target="_blank">Gemeinde Kilchberg</a>,
<a href="http://www.langnauamalbis.ch/" target="_blank">Gemeinde Langnau a.A.</a>,
<a href="http://www.richterswil.ch/" target="_blank">Gemeinde Richterswil</a>,
<a href="http://www.thalwil.ch/" target="_blank">Gemeinde Thalwil</a>,
<a href="http://www.waedenswil.ch/" target="_blank">Gemeinde Wädenswil</a>,
<a href="http://www.wieselnetz.ch/" target="_blank">Stiftung Wieselnetz</a>,
<a href="http://www.wls.ch/" target="_blank">WLS WildLife Solutions</a>,
<a href="https://aln.zh.ch/internet/baudirektion/aln/de/naturschutz.html" target="_blank">Fachstelle Naturschutz Kanton Zürich</a>,
<a href="http://www.nv-schoenenberg.ch/" target="_blank">Fachstelle Naturschutz Kanton Zürich</a>,
<a href="https://www.birdlife-zuerich.ch/home/" target="_blank">BirdLife Zürich</a>,
<a href="http://www.lsfm.zhaw.ch/de/science/institute-zentren/iunr-integrativeoekologie/geoinformatik.html" target="_blank"Forschungsgruppen Geoinformatik und Wildtiermanagement der ZHAW Wädenswil</a>,
<a href="http://www.cscf.ch/" target="_blank"> Centre Suisse de Cartographie de la Faune</a>,
<a href="http://www.cashctrl.com/de/" target="_blank">Die Schweizer Online Buchhaltung mit FREE Version.</a>,
<a href="https://wildnispark.ch/" target="_blank"> Stiftung Wildnispark Zürich</a>,
<a href="https://dokumentarfilme.ch" target="_blank">www.dokumentarfilme.ch</a>,
"Jagdgesellschaft Bocken", 
<a href="http://www.syndrega.ch/" target="_blank">Syndrega GmbH</a>,
<a href="http://www.illustrat.ch/" target="_blank">Illustrat, Atelier für Grafik und Illustration</a>,
"Harald Cigler, wissenschaftlicher Zeichner", 
<a href="http://www.schluchtalhof.ch/" target="_blank">Werner und Karin Fankhauser, Schluchtalhof Wädenswil</a>,
<a href="https://www.stallstreuli.ch/" target="_blank">Streuli Aktivstall, Horgenberg</a>,
<a href="http://www.hintermannweber.ch/" target="_blank">Hintermann Weber</a>
)

library(dplyr)

tibble(logos = "", names = names) %>%
  kableExtra::kable(col.names = c("","")) %>%
  kableExtra::column_spec(1,image = images,width = "4cm")

```



```{r,results='asis', echo = FALSE}
pander::pandoc.horizontal.rule()

pander::pandoc.link(url = glue::glue('{params$editurl}{params$rmdpath}'),text = 'Artikel bearbeiten')
```

<!--http://wieselundco.ch/ueber-uns/7-partner-->
